// =============================================================================
// Execution Plan Types (Generated by Architect, Executed by Builder)
// =============================================================================

// -----------------------------------------------------------------------------
// Plan Metadata
// -----------------------------------------------------------------------------

export interface PlanMetadata {
  name: string;
  description: string;
  complexity: 'simple' | 'moderate' | 'complex';
  estimatedSteps: number;
}

// -----------------------------------------------------------------------------
// Plan Context
// -----------------------------------------------------------------------------

export interface PlanContext {
  userIntent: string;
  existingNodes: {
    id: string;
    type: string;
    label: string;
  }[];
  existingEdges: {
    id: string;
    source: string;
    target: string;
  }[];
}

// -----------------------------------------------------------------------------
// Action Types
// -----------------------------------------------------------------------------

export interface CreateNodeAction {
  type: 'CREATE_NODE';
  nodeType: string;
  label: string;
  parentId?: string;  // Can reference ${variable}
  position?: { x: number; y: number };
  config?: Record<string, unknown>;
}

export interface ConnectNodesAction {
  type: 'CONNECT_NODES';
  sourceId: string;   // Can reference ${variable}
  targetId: string;   // Can reference ${variable}
  edgeType?: string;
}

export interface UpdateNodeAction {
  type: 'UPDATE_NODE';
  nodeId: string;     // Can reference ${variable}
  changes: {
    label?: string;
    config?: Record<string, unknown>;
  };
}

export interface DeleteNodeAction {
  type: 'DELETE_NODE';
  nodeId: string;     // Can reference ${variable}
}

export interface CreateFileAction {
  type: 'CREATE_FILE';
  path: string;       // Relative to sandbox
  content: string;
}

export interface RegisterCapabilityAction {
  type: 'REGISTER_CAPABILITY';
  name: string;
  capabilityType: 'skill' | 'hook' | 'command';
  content: string;
  triggers?: string[];
}

export type ExecutionAction =
  | CreateNodeAction
  | ConnectNodesAction
  | UpdateNodeAction
  | DeleteNodeAction
  | CreateFileAction
  | RegisterCapabilityAction;

// -----------------------------------------------------------------------------
// Execution Step
// -----------------------------------------------------------------------------

export interface ExecutionStep {
  id: string;
  order: number;
  name: string;
  description?: string;
  action: ExecutionAction;

  // Dependencies: step IDs that must complete before this step
  dependsOn: string[];

  // Output variable: store created ID for later reference
  output?: {
    nodeIdVariable?: string;   // e.g., "supervisor_id"
    edgeIdVariable?: string;
    filePathVariable?: string;
  };

  // Retry configuration
  retryCount?: number;
  retryDelayMs?: number;
}

// -----------------------------------------------------------------------------
// Execution Plan
// -----------------------------------------------------------------------------

export interface ExecutionPlan {
  id: string;
  version: '1.0';
  metadata: PlanMetadata;
  context: PlanContext;
  steps: ExecutionStep[];

  // Validation status
  validated?: boolean;
  validationErrors?: string[];
}

// -----------------------------------------------------------------------------
// Plan Execution State
// -----------------------------------------------------------------------------

export interface StepResult {
  stepId: string;
  success: boolean;
  startedAt: number;
  completedAt: number;
  result?: {
    nodeId?: string;
    edgeId?: string;
    filePath?: string;
  };
  error?: string;
}

export interface PlanExecutionState {
  planId: string;
  status: 'pending' | 'executing' | 'paused' | 'completed' | 'failed';
  currentStepIndex: number;
  stepResults: StepResult[];
  variables: Record<string, string>;
  startedAt?: number;
  completedAt?: number;
}

// -----------------------------------------------------------------------------
// Variable Resolution
// -----------------------------------------------------------------------------

/**
 * Resolves variable references like ${supervisor_id} in action parameters
 */
export function resolveVariables(
  value: string,
  variables: Record<string, string>
): string {
  return value.replace(/\$\{(\w+)\}/g, (match, varName) => {
    const resolved = variables[varName];
    if (resolved === undefined) {
      throw new Error(`Unresolved variable: ${varName}`);
    }
    return resolved;
  });
}

/**
 * Recursively resolves variables in an object
 */
export function resolveActionVariables<T extends ExecutionAction>(
  action: T,
  variables: Record<string, string>
): T {
  const resolved = JSON.parse(JSON.stringify(action));

  const resolveInObject = (obj: unknown): unknown => {
    if (typeof obj === 'string') {
      return resolveVariables(obj, variables);
    }
    if (Array.isArray(obj)) {
      return obj.map(resolveInObject);
    }
    if (obj && typeof obj === 'object') {
      const result: Record<string, unknown> = {};
      for (const [key, value] of Object.entries(obj)) {
        result[key] = resolveInObject(value);
      }
      return result;
    }
    return obj;
  };

  return resolveInObject(resolved) as T;
}
