import type { NodeTypeSchema } from './types';
import {
  commonSections,
  identityFields,
  providerOptions,
  modelsByProvider,
  toolOptions,
  permissionModeOptions,
} from './constants';

// ============================================================================
// AGENT Schema (with 16 sections and role-based visibility)
// ============================================================================

export const agentSchema: NodeTypeSchema = {
  type: 'AGENT',
  displayName: 'Agent',
  icon: 'Bot',
  color: 'text-blue-600',
  bgColor: 'bg-blue-50',
  borderColor: 'border-blue-500',
  isContainer: false,
  sections: [
    // 1. Identity (all roles)
    ...commonSections,
    // 2. Role (all roles)
    { id: 'role', label: 'Agent Role', icon: 'UserCog', defaultOpen: true, collapsible: true },
    // 3. Model (all roles)
    { id: 'model', label: 'Model', icon: 'Cpu', defaultOpen: true, collapsible: true },
    // 4. Permissions (all roles)
    { id: 'permissions', label: 'Permissions', icon: 'Lock', defaultOpen: false, collapsible: true },
    // 5. Tools (all except monitor)
    {
      id: 'tools',
      label: 'Tools',
      icon: 'Wrench',
      defaultOpen: true,
      collapsible: true,
      visibleWhen: {
        field: 'role',
        values: ['solo', 'specialist', 'member', 'planner', 'executor', 'critic',
                 'leader', 'orchestrator', 'router', 'auditor'],
      },
    },
    // 6. Capabilities (all roles)
    { id: 'capabilities', label: 'Capabilities', icon: 'Sparkles', defaultOpen: false, collapsible: true },
    // 7. System Prompt (all roles)
    { id: 'prompt', label: 'System Prompt', icon: 'MessageSquare', defaultOpen: false, collapsible: true },
    // 8. Advanced (all roles)
    { id: 'advanced', label: 'Advanced', icon: 'Settings2', defaultOpen: false, collapsible: true },
    // 9. Sub-Agent Config (coordinator category only)
    {
      id: 'subagent',
      label: 'Sub-Agent Config',
      icon: 'Users',
      description: 'Configure sub-agent spawning and management',
      defaultOpen: false,
      collapsible: true,
      visibleWhen: { field: 'role', categories: ['coordinator'] },
    },
    // 10. PAL Orchestration (coordinator category only)
    {
      id: 'pal',
      label: 'PAL Orchestration',
      icon: 'Workflow',
      description: 'Plan-Allocate-Learn orchestration phases',
      defaultOpen: false,
      collapsible: true,
      visibleWhen: { field: 'role', categories: ['coordinator'] },
    },
    // 11. Delegation (coordinator + team categories)
    {
      id: 'delegation',
      label: 'Delegation',
      icon: 'Forward',
      description: 'Task delegation settings',
      defaultOpen: false,
      collapsible: true,
      visibleWhen: { field: 'role', categories: ['coordinator', 'team'] },
    },
    // 12. Execution (executor role only)
    {
      id: 'execution',
      label: 'Execution',
      icon: 'Play',
      description: 'Execution patterns and retry policies',
      defaultOpen: false,
      collapsible: true,
      visibleWhen: { field: 'role', values: ['executor'] },
    },
    // 13. Guardrails (all roles)
    {
      id: 'guardrails',
      label: 'Guardrails',
      icon: 'Shield',
      description: 'Token limits, cost caps, and content filters',
      defaultOpen: false,
      collapsible: true,
    },
    // 14. Observability (all roles)
    {
      id: 'observability',
      label: 'Observability',
      icon: 'Eye',
      description: 'Logging, metrics, and tracing',
      defaultOpen: false,
      collapsible: true,
    },
    // 15. Memory & Context (all roles)
    {
      id: 'memory',
      label: 'Memory & Context',
      icon: 'Brain',
      description: 'Context persistence and memory management',
      defaultOpen: false,
      collapsible: true,
    },
    // 16. Monitoring (continuous category only)
    {
      id: 'monitoring',
      label: 'Monitoring',
      icon: 'Activity',
      description: 'Health checks and alerts',
      defaultOpen: false,
      collapsible: true,
      visibleWhen: { field: 'role', categories: ['continuous'] },
    },
  ],
  fields: [
    // === IDENTITY SECTION ===
    ...identityFields,
    {
      key: 'teamName',
      label: 'Team Name',
      type: 'text',
      section: 'identity',
      placeholder: 'e.g., Research Team',
    },

    // === ROLE SECTION ===
    {
      key: 'role',
      label: 'Role',
      type: 'roleSelect',
      section: 'role',
      defaultValue: 'member',
      description: 'Determines available configuration sections',
    },

    // === MODEL SECTION ===
    {
      key: 'provider',
      label: 'Provider',
      type: 'select',
      section: 'model',
      options: providerOptions,
      defaultValue: 'anthropic',
    },
    {
      key: 'model',
      label: 'Model',
      type: 'select',
      section: 'model',
      options: modelsByProvider['anthropic'],
      dependsOn: 'provider',
      defaultValue: 'claude-sonnet-4-5-20250929',
    },
    {
      key: 'temperature',
      label: 'Temperature',
      type: 'slider',
      section: 'model',
      description: '0 = Precise, 1 = Creative',
      defaultValue: 0.7,
      validation: { min: 0, max: 1 },
      width: 'half',
      lockedWhen: {
        roles: ['executor'],
        value: 0,
        reason: 'Executors require deterministic behavior (temperature=0)',
      },
    },
    {
      key: 'thinkingMode',
      label: 'Thinking Mode',
      type: 'select',
      section: 'model',
      description: 'Extended reasoning depth for complex tasks (increases token usage)',
      options: [
        { label: 'None', value: 'none', description: 'Standard inference - fastest' },
        { label: 'Low', value: 'low', description: 'Light reasoning (~2x tokens)' },
        { label: 'Medium', value: 'medium', description: 'Moderate reasoning (~4x tokens)' },
        { label: 'High', value: 'high', description: 'Deep reasoning (~8x tokens)' },
        { label: 'Max', value: 'max', description: 'Maximum reasoning depth' },
      ],
      defaultValue: 'none',
      width: 'half',
      lockedWhen: {
        roles: ['executor', 'router', 'monitor'],
        value: 'none',
        reason: 'This role requires standard inference without extended thinking',
      },
    },
    {
      key: 'contextWindow',
      label: 'Context Window',
      type: 'select',
      section: 'model',
      description: 'Maximum context size (affects cost and capability)',
      options: [
        { label: '8K', value: 8192 },
        { label: '16K', value: 16384 },
        { label: '32K', value: 32768 },
        { label: '64K', value: 65536 },
        { label: '128K', value: 131072 },
        { label: '200K', value: 200000 },
      ],
      defaultValue: 200000,
      width: 'half',
    },
    {
      key: 'reservedOutputTokens',
      label: 'Reserved Output Tokens',
      type: 'number',
      section: 'model',
      description: 'Tokens reserved for response generation',
      defaultValue: 16000,
      validation: { min: 1000, max: 64000 },
      width: 'half',
    },

    // === PERMISSIONS SECTION ===
    {
      key: 'permissionMode',
      label: 'Permission Mode',
      type: 'select',
      section: 'permissions',
      options: permissionModeOptions,
      defaultValue: 'default',
    },
    {
      key: 'disallowedTools',
      label: 'Disallowed Tools',
      type: 'chips',
      section: 'permissions',
      description: 'Tools this agent cannot use',
      options: toolOptions,
      defaultValue: [],
    },
    {
      key: 'fileAccessPatterns',
      label: 'File Access Patterns',
      type: 'tags',
      section: 'permissions',
      description: 'Glob patterns for allowed file access (e.g., src/**/*.ts)',
      placeholder: 'Add pattern...',
      defaultValue: [],
    },
    {
      key: 'requiresApprovalFor',
      label: 'Requires Approval For',
      type: 'chips',
      section: 'permissions',
      description: 'Actions that require human approval',
      options: [
        { label: 'File Writes', value: 'file_writes' },
        { label: 'File Deletes', value: 'file_deletes' },
        { label: 'Shell Commands', value: 'shell_commands' },
        { label: 'External APIs', value: 'external_apis' },
        { label: 'Git Operations', value: 'git_operations' },
      ],
      defaultValue: [],
    },

    // === TOOLS SECTION ===
    {
      key: 'tools',
      label: 'Available Tools',
      type: 'chips',
      section: 'tools',
      options: toolOptions,
      defaultValue: ['Read', 'Edit', 'Bash', 'Glob', 'Grep'],
    },

    // === CAPABILITIES SECTION ===
    {
      key: 'skills',
      label: 'Skills',
      type: 'capabilities',
      section: 'capabilities',
      description: 'Skills this agent can use',
      placeholder: 'Add skill...',
    },
    {
      key: 'mcps',
      label: 'MCP Servers',
      type: 'capabilities',
      section: 'capabilities',
      description: 'MCP servers to connect',
      placeholder: 'Add MCP...',
    },
    {
      key: 'commands',
      label: 'Commands',
      type: 'capabilities',
      section: 'capabilities',
      description: 'Slash commands this agent handles',
      placeholder: 'Add command...',
    },

    // === SYSTEM PROMPT SECTION ===
    {
      key: 'systemPrompt',
      label: 'System Prompt',
      type: 'textarea',
      section: 'prompt',
      placeholder: 'You are a helpful assistant specialized in...',
      validation: { maxLength: 10000 },
    },

    // === ADVANCED SECTION ===
    {
      key: 'maxTokens',
      label: 'Max Tokens',
      type: 'number',
      section: 'advanced',
      placeholder: '4096',
      defaultValue: 4096,
      validation: { min: 256, max: 128000 },
      width: 'half',
    },
    {
      key: 'topP',
      label: 'Top P',
      type: 'slider',
      section: 'advanced',
      defaultValue: 1.0,
      validation: { min: 0.1, max: 1 },
      width: 'half',
    },
    {
      key: 'failoverChain',
      label: 'Failover Agents',
      type: 'chips',
      section: 'advanced',
      description: 'Backup agents if this one fails',
    },

    // === SUB-AGENT CONFIG SECTION (coordinator only) ===
    {
      key: 'subAgentConfig.spawnRules.maxSubagents',
      label: 'Max Sub-agents',
      type: 'number',
      section: 'subagent',
      placeholder: '5',
      defaultValue: 5,
      validation: { min: 1, max: 20 },
      width: 'half',
    },
    {
      key: 'subAgentConfig.spawnRules.autoSpawn',
      label: 'Auto-spawn Sub-agents',
      type: 'checkbox',
      section: 'subagent',
      description: 'Automatically spawn sub-agents when needed',
      defaultValue: false,
    },
    {
      key: 'subAgentConfig.spawnRules.inheritConfig',
      label: 'Inherit Configuration',
      type: 'checkbox',
      section: 'subagent',
      description: 'Sub-agents inherit parent configuration',
      defaultValue: true,
    },
    {
      key: 'subAgentConfig.communication',
      label: 'Communication Mode',
      type: 'select',
      section: 'subagent',
      options: [
        { label: 'Synchronous', value: 'sync', description: 'Wait for each sub-agent' },
        { label: 'Asynchronous', value: 'async', description: 'Fire and forget' },
        { label: 'Event-driven', value: 'event-driven', description: 'React to events' },
      ],
      defaultValue: 'sync',
    },
    {
      key: 'subAgentConfig.resultAggregation',
      label: 'Result Aggregation',
      type: 'select',
      section: 'subagent',
      options: [
        { label: 'Merge All', value: 'merge', description: 'Combine all results' },
        { label: 'First Response', value: 'first', description: 'Use first result' },
        { label: 'Voting', value: 'vote', description: 'Consensus-based' },
        { label: 'Custom', value: 'custom', description: 'Custom aggregation' },
      ],
      defaultValue: 'merge',
    },
    {
      key: 'subAgentConfig.spawningMode',
      label: 'Spawning Mode',
      type: 'select',
      section: 'subagent',
      description: 'How sub-agents are created and managed',
      options: [
        { label: 'Eager', value: 'eager', description: 'Pre-spawn all sub-agents' },
        { label: 'Lazy', value: 'lazy', description: 'Spawn only when needed' },
        { label: 'On-demand', value: 'on-demand', description: 'Create per-task' },
        { label: 'Pooled', value: 'pooled', description: 'Use agent pool' },
      ],
      defaultValue: 'lazy',
    },
    {
      key: 'subAgentConfig.delegationDepth',
      label: 'Delegation Depth',
      type: 'number',
      section: 'subagent',
      description: 'Maximum levels of nested delegation (1-5)',
      defaultValue: 2,
      validation: { min: 1, max: 5 },
      width: 'half',
    },
    {
      key: 'subAgentConfig.isolatedContext',
      label: 'Isolated Context',
      type: 'checkbox',
      section: 'subagent',
      description: 'Sub-agents have isolated memory context',
      defaultValue: false,
    },
    {
      key: 'subAgentConfig.agentIdFormat',
      label: 'Agent ID Format',
      type: 'select',
      section: 'subagent',
      description: 'Format for generated sub-agent IDs',
      options: [
        { label: 'UUID', value: 'uuid', description: 'Random UUID' },
        { label: 'Sequential', value: 'sequential', description: 'parent-1, parent-2, ...' },
        { label: 'Hierarchical', value: 'hierarchical', description: 'parent.child.grandchild' },
      ],
      defaultValue: 'hierarchical',
      width: 'half',
    },
    {
      key: 'subAgentConfig.inheritance.tools',
      label: 'Inherit Tools',
      type: 'checkbox',
      section: 'subagent',
      description: 'Sub-agents inherit parent tools',
      defaultValue: true,
    },
    {
      key: 'subAgentConfig.inheritance.skills',
      label: 'Inherit Skills',
      type: 'checkbox',
      section: 'subagent',
      description: 'Sub-agents inherit parent skills',
      defaultValue: true,
    },
    {
      key: 'subAgentConfig.inheritance.permissions',
      label: 'Inherit Permissions',
      type: 'checkbox',
      section: 'subagent',
      description: 'Sub-agents inherit parent permission settings',
      defaultValue: true,
    },
    {
      key: 'subAgentConfig.inheritance.guardrails',
      label: 'Inherit Guardrails',
      type: 'checkbox',
      section: 'subagent',
      description: 'Sub-agents inherit parent guardrails',
      defaultValue: true,
    },

    // === PAL ORCHESTRATION SECTION (coordinator only) ===
    {
      key: 'palConfig.planPhase.enabled',
      label: 'Enable Planning Phase',
      type: 'checkbox',
      section: 'pal',
      description: 'Generate detailed plans before execution',
      defaultValue: true,
    },
    {
      key: 'palConfig.planPhase.maxPlanningTokens',
      label: 'Max Planning Tokens',
      type: 'number',
      section: 'pal',
      placeholder: '2000',
      defaultValue: 2000,
      validation: { min: 500, max: 10000 },
      width: 'half',
      conditional: { field: 'palConfig.planPhase.enabled', value: true },
    },
    {
      key: 'palConfig.planPhase.requireApproval',
      label: 'Require Plan Approval',
      type: 'checkbox',
      section: 'pal',
      description: 'User must approve plan before execution',
      defaultValue: false,
      conditional: { field: 'palConfig.planPhase.enabled', value: true },
    },
    {
      key: 'palConfig.allocatePhase.strategy',
      label: 'Allocation Strategy',
      type: 'select',
      section: 'pal',
      options: [
        { label: 'Sequential', value: 'sequential', description: 'One task at a time' },
        { label: 'Parallel', value: 'parallel', description: 'Multiple concurrent tasks' },
        { label: 'Adaptive', value: 'adaptive', description: 'Dynamic based on load' },
      ],
      defaultValue: 'adaptive',
    },
    {
      key: 'palConfig.allocatePhase.maxConcurrency',
      label: 'Max Concurrency',
      type: 'number',
      section: 'pal',
      placeholder: '3',
      defaultValue: 3,
      validation: { min: 1, max: 10 },
      width: 'half',
      conditional: { field: 'palConfig.allocatePhase.strategy', value: 'parallel' },
    },
    {
      key: 'palConfig.learnPhase.enabled',
      label: 'Enable Learning Phase',
      type: 'checkbox',
      section: 'pal',
      description: 'Learn from execution results',
      defaultValue: true,
    },
    {
      key: 'palConfig.learnPhase.feedbackLoop',
      label: 'Feedback Loop',
      type: 'checkbox',
      section: 'pal',
      description: 'Incorporate learnings into future plans',
      defaultValue: true,
      conditional: { field: 'palConfig.learnPhase.enabled', value: true },
    },
    {
      key: 'palConfig.learnPhase.memoryIntegration',
      label: 'Memory Integration',
      type: 'checkbox',
      section: 'pal',
      description: 'Store learnings in long-term memory',
      defaultValue: false,
      conditional: { field: 'palConfig.learnPhase.enabled', value: true },
    },
    {
      key: 'palConfig.palTools',
      label: 'PAL Tools',
      type: 'chips',
      section: 'pal',
      description: 'Tools available during PAL orchestration',
      options: [
        { label: 'TodoWrite', value: 'TodoWrite' },
        { label: 'Task', value: 'Task' },
        { label: 'EnterPlanMode', value: 'EnterPlanMode' },
        { label: 'ExitPlanMode', value: 'ExitPlanMode' },
      ],
      defaultValue: ['TodoWrite', 'Task'],
    },
    {
      key: 'palConfig.consensusConfig.enabled',
      label: 'Enable Consensus',
      type: 'checkbox',
      section: 'pal',
      description: 'Require agreement from multiple agents',
      defaultValue: false,
    },
    {
      key: 'palConfig.consensusConfig.threshold',
      label: 'Consensus Threshold',
      type: 'slider',
      section: 'pal',
      description: 'Percentage of agents that must agree (0-100%)',
      defaultValue: 0.67,
      validation: { min: 0.5, max: 1 },
      width: 'half',
      conditional: { field: 'palConfig.consensusConfig.enabled', value: true },
    },
    {
      key: 'palConfig.consensusConfig.votingMethod',
      label: 'Voting Method',
      type: 'select',
      section: 'pal',
      options: [
        { label: 'Majority', value: 'majority' },
        { label: 'Unanimous', value: 'unanimous' },
        { label: 'Weighted', value: 'weighted' },
      ],
      defaultValue: 'majority',
      width: 'half',
      conditional: { field: 'palConfig.consensusConfig.enabled', value: true },
    },
    {
      key: 'palConfig.contextRevival.enabled',
      label: 'Enable Context Revival',
      type: 'checkbox',
      section: 'pal',
      description: 'Restore context from previous sessions',
      defaultValue: false,
    },
    {
      key: 'palConfig.contextRevival.maxAge',
      label: 'Max Context Age (hours)',
      type: 'number',
      section: 'pal',
      description: 'Maximum age of context to restore',
      defaultValue: 24,
      validation: { min: 1, max: 168 },
      width: 'half',
      conditional: { field: 'palConfig.contextRevival.enabled', value: true },
    },
    {
      key: 'palConfig.contextRevival.priorityFields',
      label: 'Priority Fields',
      type: 'chips',
      section: 'pal',
      description: 'Fields to prioritize when restoring context',
      options: [
        { label: 'Goals', value: 'goals' },
        { label: 'Progress', value: 'progress' },
        { label: 'Errors', value: 'errors' },
        { label: 'Decisions', value: 'decisions' },
      ],
      defaultValue: ['goals', 'progress'],
      conditional: { field: 'palConfig.contextRevival.enabled', value: true },
    },

    // === DELEGATION SECTION (coordinator + team) ===
    {
      key: 'delegation.allowDelegation',
      label: 'Allow Delegation',
      type: 'checkbox',
      section: 'delegation',
      description: 'This agent can delegate tasks to others',
      defaultValue: true,
    },
    {
      key: 'delegation.delegationStrategy',
      label: 'Delegation Strategy',
      type: 'select',
      section: 'delegation',
      options: [
        { label: 'Capability-based', value: 'capability-based', description: 'Match by skills' },
        { label: 'Load-balanced', value: 'load-balanced', description: 'Distribute evenly' },
        { label: 'Round-robin', value: 'round-robin', description: 'Rotate assignment' },
      ],
      defaultValue: 'capability-based',
      conditional: { field: 'delegation.allowDelegation', value: true },
    },
    {
      key: 'delegation.escalationPath',
      label: 'Escalation Path',
      type: 'chips',
      section: 'delegation',
      description: 'Agent IDs for escalation (in order)',
      placeholder: 'Add agent ID...',
    },
    {
      key: 'delegation.autoDelegate',
      label: 'Auto-delegate',
      type: 'checkbox',
      section: 'delegation',
      description: 'Automatically delegate based on capability matching',
      defaultValue: false,
      conditional: { field: 'delegation.allowDelegation', value: true },
    },

    // === EXECUTION SECTION (executor role only) ===
    {
      key: 'execution.executionMode',
      label: 'Execution Mode',
      type: 'select',
      section: 'execution',
      options: [
        { label: 'Strict', value: 'strict', description: 'Follow plan exactly' },
        { label: 'Adaptive', value: 'adaptive', description: 'Minor adjustments allowed' },
        { label: 'Exploratory', value: 'exploratory', description: 'Explore alternatives' },
      ],
      defaultValue: 'strict',
    },
    {
      key: 'execution.retryPolicy.maxRetries',
      label: 'Max Retries',
      type: 'number',
      section: 'execution',
      placeholder: '3',
      defaultValue: 3,
      validation: { min: 0, max: 10 },
      width: 'half',
    },
    {
      key: 'execution.retryPolicy.backoffMs',
      label: 'Backoff (ms)',
      type: 'number',
      section: 'execution',
      placeholder: '1000',
      defaultValue: 1000,
      validation: { min: 100, max: 60000 },
      width: 'half',
    },
    {
      key: 'execution.retryPolicy.exponential',
      label: 'Exponential Backoff',
      type: 'checkbox',
      section: 'execution',
      description: 'Double backoff time on each retry',
      defaultValue: true,
    },
    {
      key: 'execution.checkpointing',
      label: 'Enable Checkpointing',
      type: 'checkbox',
      section: 'execution',
      description: 'Save progress at each step',
      defaultValue: true,
    },
    {
      key: 'execution.rollbackOnFailure',
      label: 'Rollback on Failure',
      type: 'checkbox',
      section: 'execution',
      description: 'Revert changes if execution fails',
      defaultValue: false,
    },

    // === GUARDRAILS SECTION (all roles) ===
    {
      key: 'guardrails.tokenLimit',
      label: 'Token Limit',
      type: 'number',
      section: 'guardrails',
      placeholder: '100000',
      defaultValue: 100000,
      description: 'Maximum tokens per session',
      validation: { min: 1000, max: 1000000 },
      width: 'half',
    },
    {
      key: 'guardrails.costCap',
      label: 'Cost Cap ($)',
      type: 'number',
      section: 'guardrails',
      placeholder: '10.00',
      description: 'Maximum cost per session in dollars',
      validation: { min: 0.01, max: 1000 },
      width: 'half',
    },
    {
      key: 'guardrails.timeoutSeconds',
      label: 'Timeout (seconds)',
      type: 'number',
      section: 'guardrails',
      placeholder: '300',
      defaultValue: 300,
      validation: { min: 30, max: 3600 },
      width: 'half',
    },
    {
      key: 'guardrails.maxRetries',
      label: 'Max Retries',
      type: 'number',
      section: 'guardrails',
      placeholder: '3',
      defaultValue: 3,
      validation: { min: 0, max: 10 },
      width: 'half',
    },
    {
      key: 'guardrails.contentFilters.profanity',
      label: 'Filter Profanity',
      type: 'checkbox',
      section: 'guardrails',
      defaultValue: true,
      width: 'half',
    },
    {
      key: 'guardrails.contentFilters.pii',
      label: 'Filter PII',
      type: 'checkbox',
      section: 'guardrails',
      description: 'Block personally identifiable information',
      defaultValue: true,
      width: 'half',
    },
    {
      key: 'guardrails.contentFilters.injection',
      label: 'Prompt Injection Detection',
      type: 'checkbox',
      section: 'guardrails',
      description: 'Detect and block prompt injection attempts',
      defaultValue: true,
    },

    // === OBSERVABILITY SECTION (all roles) ===
    {
      key: 'observability.logging.level',
      label: 'Log Level',
      type: 'select',
      section: 'observability',
      options: [
        { label: 'Debug', value: 'debug' },
        { label: 'Info', value: 'info' },
        { label: 'Warn', value: 'warn' },
        { label: 'Error', value: 'error' },
      ],
      defaultValue: 'info',
      width: 'half',
    },
    {
      key: 'observability.logging.destinations',
      label: 'Log Destinations',
      type: 'chips',
      section: 'observability',
      description: 'Where to send logs',
      placeholder: 'e.g., console, file, remote',
      defaultValue: ['console'],
    },
    {
      key: 'observability.metrics.enabled',
      label: 'Enable Metrics',
      type: 'checkbox',
      section: 'observability',
      defaultValue: true,
      width: 'half',
    },
    {
      key: 'observability.metrics.exportInterval',
      label: 'Export Interval (sec)',
      type: 'number',
      section: 'observability',
      placeholder: '60',
      defaultValue: 60,
      validation: { min: 10, max: 3600 },
      width: 'half',
      conditional: { field: 'observability.metrics.enabled', value: true },
    },
    {
      key: 'observability.tracing.enabled',
      label: 'Enable Tracing',
      type: 'checkbox',
      section: 'observability',
      defaultValue: false,
      width: 'half',
    },
    {
      key: 'observability.tracing.samplingRate',
      label: 'Sampling Rate',
      type: 'slider',
      section: 'observability',
      description: '0 = none, 1 = all traces',
      defaultValue: 0.1,
      validation: { min: 0, max: 1 },
      width: 'half',
      conditional: { field: 'observability.tracing.enabled', value: true },
    },

    // === MEMORY & CONTEXT SECTION (all roles) ===
    {
      key: 'memory.contextPersistence',
      label: 'Context Persistence',
      type: 'select',
      section: 'memory',
      options: [
        { label: 'None', value: 'none', description: 'No persistence' },
        { label: 'Session', value: 'session', description: 'Within session only' },
        { label: 'Persistent', value: 'persistent', description: 'Across sessions' },
      ],
      defaultValue: 'session',
    },
    {
      key: 'memory.memoryType',
      label: 'Memory Type',
      type: 'select',
      section: 'memory',
      options: [
        { label: 'Short-term', value: 'short-term', description: 'Recent context only' },
        { label: 'Long-term', value: 'long-term', description: 'Accumulated knowledge' },
        { label: 'Both', value: 'both', description: 'Short and long-term' },
      ],
      defaultValue: 'short-term',
    },
    {
      key: 'memory.maxContextTokens',
      label: 'Max Context Tokens',
      type: 'number',
      section: 'memory',
      placeholder: '8000',
      defaultValue: 8000,
      validation: { min: 1000, max: 200000 },
      width: 'half',
    },
    {
      key: 'memory.summarizationThreshold',
      label: 'Summarization Threshold',
      type: 'number',
      section: 'memory',
      description: 'Token count to trigger summarization',
      placeholder: '6000',
      defaultValue: 6000,
      validation: { min: 1000, max: 100000 },
      width: 'half',
    },

    // === MONITORING SECTION (continuous category only) ===
    {
      key: 'monitoring.healthChecks.interval',
      label: 'Health Check Interval (sec)',
      type: 'number',
      section: 'monitoring',
      placeholder: '60',
      defaultValue: 60,
      validation: { min: 10, max: 3600 },
      width: 'half',
    },
    {
      key: 'monitoring.healthChecks.endpoints',
      label: 'Health Endpoints',
      type: 'chips',
      section: 'monitoring',
      description: 'Endpoints to monitor',
      placeholder: 'Add endpoint URL...',
    },
    {
      key: 'monitoring.alerts.enabled',
      label: 'Enable Alerts',
      type: 'checkbox',
      section: 'monitoring',
      defaultValue: true,
      width: 'half',
    },
    {
      key: 'monitoring.alerts.channels',
      label: 'Alert Channels',
      type: 'chips',
      section: 'monitoring',
      description: 'Where to send alerts',
      placeholder: 'e.g., slack, email',
      defaultValue: ['slack'],
      conditional: { field: 'monitoring.alerts.enabled', value: true },
    },
    {
      key: 'monitoring.alerts.escalation',
      label: 'Enable Escalation',
      type: 'checkbox',
      section: 'monitoring',
      description: 'Escalate unacknowledged alerts',
      defaultValue: true,
      conditional: { field: 'monitoring.alerts.enabled', value: true },
    },
    {
      key: 'monitoring.dashboards',
      label: 'Dashboards',
      type: 'chips',
      section: 'monitoring',
      description: 'Dashboard identifiers',
      placeholder: 'Add dashboard ID...',
    },
  ],
};
