import type { NodeTypeSchema } from './types';
import {
  commonSections,
  identityFields,
  hookEventOptions,
  authTypeOptions,
} from './constants';

// ============================================================================
// Capability Node Schemas: MCP_SERVER, SKILL, HOOK
// ============================================================================

export const mcpServerSchema: NodeTypeSchema = {
  type: 'MCP_SERVER',
  displayName: 'MCP Server',
  icon: 'Server',
  color: 'text-violet-600',
  bgColor: 'bg-violet-50',
  borderColor: 'border-violet-500',
  isContainer: false,
  sections: [
    ...commonSections,
    { id: 'command', label: 'Command', icon: 'Terminal', defaultOpen: true, collapsible: true },
    { id: 'environment', label: 'Environment', icon: 'FileCode', defaultOpen: true, collapsible: true },
    { id: 'auth', label: 'Authentication', icon: 'Key', defaultOpen: false, collapsible: true },
    { id: 'limits', label: 'Rate Limits', icon: 'Gauge', defaultOpen: false, collapsible: true },
  ],
  fields: [
    ...identityFields,
    {
      key: 'command',
      label: 'Command',
      type: 'text',
      section: 'command',
      placeholder: 'npx, uvx, node, python...',
      description: 'The command to start the MCP server',
      validation: { required: true },
    },
    {
      key: 'args',
      label: 'Arguments',
      type: 'chips',
      section: 'command',
      placeholder: 'Add argument...',
      description: 'Command line arguments',
    },
    {
      key: 'env',
      label: 'Environment Variables',
      type: 'keyvalue',
      section: 'environment',
      description: 'Environment variables for the server',
      placeholder: 'KEY=value',
    },
    {
      key: 'auth.type',
      label: 'Auth Type',
      type: 'select',
      section: 'auth',
      options: authTypeOptions,
      defaultValue: 'api_key',
    },
    {
      key: 'auth.envVar',
      label: 'Credential Env Var',
      type: 'text',
      section: 'auth',
      placeholder: 'e.g., GITHUB_TOKEN',
      description: 'Environment variable containing the credential',
      conditional: { field: 'auth.type', value: 'none', operator: 'neq' },
    },
    {
      key: 'rateLimit.requestsPerMinute',
      label: 'Requests/Minute',
      type: 'number',
      section: 'limits',
      placeholder: '60',
      defaultValue: 60,
      validation: { min: 1, max: 10000 },
      width: 'half',
    },
    {
      key: 'rateLimit.tokensPerMinute',
      label: 'Tokens/Minute',
      type: 'number',
      section: 'limits',
      placeholder: '100000',
      defaultValue: 100000,
      validation: { min: 1000, max: 1000000 },
      width: 'half',
    },
    {
      key: 'timeout',
      label: 'Timeout (ms)',
      type: 'number',
      section: 'limits',
      placeholder: '30000',
      defaultValue: 30000,
      validation: { min: 1000, max: 300000 },
      width: 'half',
    },
    {
      key: 'retryCount',
      label: 'Retry Count',
      type: 'number',
      section: 'limits',
      placeholder: '3',
      defaultValue: 3,
      validation: { min: 0, max: 10 },
      width: 'half',
    },
  ],
};

export const skillSchema: NodeTypeSchema = {
  type: 'SKILL',
  displayName: 'Skill',
  icon: 'Sparkles',
  color: 'text-green-600',
  bgColor: 'bg-green-50',
  borderColor: 'border-green-500',
  isContainer: false,
  sections: [
    ...commonSections,
    { id: 'triggers', label: 'Triggers', icon: 'Zap', defaultOpen: true, collapsible: true },
    { id: 'behavior', label: 'Behavior', icon: 'Sliders', defaultOpen: false, collapsible: true },
    { id: 'content', label: 'Content', icon: 'FileText', defaultOpen: false, collapsible: true },
  ],
  fields: [
    ...identityFields,
    {
      key: 'triggers.keywords',
      label: 'Trigger Keywords',
      type: 'chips',
      section: 'triggers',
      placeholder: 'Add keyword...',
      description: 'Words that activate this skill',
    },
    {
      key: 'triggers.filePatterns',
      label: 'File Patterns',
      type: 'chips',
      section: 'triggers',
      placeholder: 'e.g., **/*.tsx',
      description: 'Glob patterns for file-based activation',
    },
    {
      key: 'triggers.commands',
      label: 'Commands',
      type: 'chips',
      section: 'triggers',
      placeholder: 'e.g., /code-review',
      description: 'Slash commands that trigger this skill',
    },
    {
      key: 'autoActivate',
      label: 'Auto Activate',
      type: 'checkbox',
      section: 'behavior',
      description: 'Automatically load when triggers match',
      defaultValue: true,
    },
    {
      key: 'priority',
      label: 'Priority',
      type: 'slider',
      section: 'behavior',
      description: 'Higher priority skills load first',
      defaultValue: 5,
      validation: { min: 1, max: 10 },
      width: 'half',
    },
    {
      key: 'maxTokens',
      label: 'Max Tokens',
      type: 'number',
      section: 'behavior',
      description: 'Token budget for this skill',
      placeholder: '5000',
      defaultValue: 5000,
      validation: { min: 100, max: 50000 },
      width: 'half',
    },
    {
      key: 'content',
      label: 'Skill Content',
      type: 'textarea',
      section: 'content',
      placeholder: '# Skill Name\n\n## Instructions\n...',
      description: 'Markdown content for the skill',
      validation: { maxLength: 50000 },
    },
  ],
};

export const hookSchema: NodeTypeSchema = {
  type: 'HOOK',
  displayName: 'Hook',
  icon: 'Anchor',
  color: 'text-pink-600',
  bgColor: 'bg-pink-50',
  borderColor: 'border-pink-500',
  isContainer: false,
  sections: [
    ...commonSections,
    { id: 'trigger', label: 'Trigger', icon: 'Zap', defaultOpen: true, collapsible: true },
    { id: 'action', label: 'Action', icon: 'Play', defaultOpen: true, collapsible: true },
    { id: 'options', label: 'Options', icon: 'Settings', defaultOpen: false, collapsible: true },
  ],
  fields: [
    ...identityFields,
    {
      key: 'event',
      label: 'Event',
      type: 'select',
      section: 'trigger',
      options: hookEventOptions,
      defaultValue: 'PostToolUse',
      validation: { required: true },
    },
    {
      key: 'matcher',
      label: 'Matcher Pattern',
      type: 'text',
      section: 'trigger',
      placeholder: 'e.g., Write|Edit',
      description: 'Tool name or regex pattern to match',
    },
    {
      key: 'command',
      label: 'Command',
      type: 'textarea',
      section: 'action',
      placeholder: 'npm run lint ${file}',
      description: 'Shell command to execute',
      validation: { required: true },
    },
    {
      key: 'timeout',
      label: 'Timeout (seconds)',
      type: 'number',
      section: 'options',
      placeholder: '30',
      defaultValue: 30,
      validation: { min: 1, max: 300 },
      width: 'half',
    },
    {
      key: 'onError',
      label: 'On Error',
      type: 'select',
      section: 'options',
      options: [
        { label: 'Ignore', value: 'ignore', description: 'Continue silently' },
        { label: 'Warn', value: 'warn', description: 'Show warning but continue' },
        { label: 'Fail', value: 'fail', description: 'Stop execution' },
      ],
      defaultValue: 'warn',
      width: 'half',
    },
    {
      key: 'environment',
      label: 'Environment Variables',
      type: 'keyvalue',
      section: 'options',
      description: 'Additional environment variables',
    },
  ],
};
