import { describe, it, expect } from 'vitest';
import { Node, Edge } from 'reactflow';
import { generateExport } from '@/utils/export/generators';
import type { WorkflowConfig } from '@/types/config';
import type { NodeData } from '@/types/core';
import {
  DEFAULT_FRAMEWORK_OPTIONS,
  DEFAULT_MODEL_CONFIG,
} from '@/types/config';
import mockCanvas from '../fixtures/mock-canvas.json';

const nodes = mockCanvas.nodes as unknown as Node<NodeData>[];
const edges = mockCanvas.edges as unknown as Edge[];

const workflowConfig: WorkflowConfig = {
  name: 'Research Pipeline',
  description: 'A 3-agent research and writing pipeline',
  version: '1.0.0',
  framework: 'vab-native',
  skillSchema: 'agentskills',
  frameworkOptions: DEFAULT_FRAMEWORK_OPTIONS,
  defaultModel: DEFAULT_MODEL_CONFIG,
  environment: 'development',
};

describe('VABNativeGenerator CLAUDE.md output', () => {
  const result = generateExport(nodes, edges, workflowConfig);

  it('succeeds without errors', () => {
    expect(result.success).toBe(true);
    expect(result.errors).toHaveLength(0);
  });

  it('produces a CLAUDE.md file', () => {
    const claudeMd = result.files.find((f) => f.path === 'CLAUDE.md');
    expect(claudeMd).toBeDefined();
    expect(claudeMd!.content.length).toBeGreaterThan(0);
  });

  it('CLAUDE.md starts with a top-level heading', () => {
    const claudeMd = result.files.find((f) => f.path === 'CLAUDE.md')!;
    expect(claudeMd.content).toMatch(/^# Research Pipeline/);
  });

  it('CLAUDE.md includes the description as a blockquote', () => {
    const claudeMd = result.files.find((f) => f.path === 'CLAUDE.md')!;
    expect(claudeMd.content).toContain(
      '> A 3-agent research and writing pipeline',
    );
  });

  it('CLAUDE.md contains Quick Start section', () => {
    const claudeMd = result.files.find((f) => f.path === 'CLAUDE.md')!;
    expect(claudeMd.content).toContain('## Quick Start');
    expect(claudeMd.content).toContain('claude --config .');
  });

  it('CLAUDE.md contains Architecture Overview with mermaid diagram', () => {
    const claudeMd = result.files.find((f) => f.path === 'CLAUDE.md')!;
    expect(claudeMd.content).toContain('## Architecture Overview');
    expect(claudeMd.content).toContain('```mermaid');
    expect(claudeMd.content).toContain('graph TB');
  });

  it('CLAUDE.md contains Agents section with table', () => {
    const claudeMd = result.files.find((f) => f.path === 'CLAUDE.md')!;
    expect(claudeMd.content).toContain('## Agents');
    expect(claudeMd.content).toContain('| Agent | Role | Model | Tools |');
    expect(claudeMd.content).toContain('Planner');
    expect(claudeMd.content).toContain('Researcher');
    expect(claudeMd.content).toContain('Writer');
  });

  it('CLAUDE.md contains generated-by footer', () => {
    const claudeMd = result.files.find((f) => f.path === 'CLAUDE.md')!;
    expect(claudeMd.content).toContain('*Generated by Visual Agent Builder');
  });

  it('produces one agent markdown file per agent node', () => {
    const agentFiles = result.files.filter((f) =>
      f.path.startsWith('agents/'),
    );
    expect(agentFiles).toHaveLength(3);
  });

  it('agent markdown files contain YAML frontmatter', () => {
    const agentFiles = result.files.filter((f) =>
      f.path.startsWith('agents/'),
    );
    for (const file of agentFiles) {
      expect(file.content).toMatch(/^---\n/);
      expect(file.content).toContain('name:');
      expect(file.content).toContain('role:');
    }
  });

  it('agent markdown files contain system prompts', () => {
    const agentFiles = result.files.filter((f) =>
      f.path.startsWith('agents/'),
    );
    for (const file of agentFiles) {
      expect(file.content).toContain('## System Prompt');
    }
  });

  it('produces a README.md when generateReadme is true', () => {
    const readme = result.files.find((f) => f.path === 'README.md');
    expect(readme).toBeDefined();
    expect(readme!.content).toContain('## Setup');
    expect(readme!.content).toContain('## Structure');
  });

  it('metadata reports correct file count', () => {
    expect(result.metadata.fileCount).toBe(result.files.length);
    expect(result.metadata.framework).toBe('vab-native');
    expect(result.metadata.version).toBe('1.0.0');
  });

  it('metadata totalSize matches actual content length', () => {
    const actualSize = result.files.reduce(
      (sum, f) => sum + f.content.length,
      0,
    );
    expect(result.metadata.totalSize).toBe(actualSize);
  });
});
