import { ExportResult } from '../../types';
import { BaseExportGenerator } from '../base';

/**
 * CrewAI Export Generator.
 * Generates a Python project with role-playing agent crews.
 */
export class CrewAIGenerator extends BaseExportGenerator {
  generate(): ExportResult {
    // Validate first
    if (!this.validate()) {
      return this.buildResult();
    }

    // Generate project files
    this.addFile('README.md', this.generateReadme());
    this.addFile('pyproject.toml', this.generatePyProject());
    this.addFile('requirements.txt', this.generateRequirements());
    this.addFile('.env.example', this.generateEnvExample());

    // Generate config files
    this.addFile('config/agents.yaml', this.generateAgentsYaml());
    this.addFile('config/tasks.yaml', this.generateTasksYaml());

    // Generate Python source files
    this.addFile('src/__init__.py', '# CrewAI workflow package\n');
    this.addFile('src/main.py', this.generateMain());
    this.addFile('src/crew.py', this.generateCrew());

    // Generate agent class files
    this.generateAgentClasses();

    // Generate task class files
    this.generateTaskClasses();

    return this.buildResult();
  }

  private generateReadme(): string {
    return `# ${this.config.name}

${this.config.description || 'CrewAI-based multi-agent workflow.'}

## Setup

\`\`\`bash
# Create virtual environment
python -m venv venv
source venv/bin/activate  # or venv\\Scripts\\activate on Windows

# Install dependencies
pip install -e .

# Set environment variables
cp .env.example .env
# Edit .env with your API keys
\`\`\`

## Usage

\`\`\`bash
# Run the crew
python -m src.main "Your task or query here"

# With hierarchical process
python -m src.main --process hierarchical "Your task"
\`\`\`

## Project Structure

\`\`\`
.
├── config/
│   ├── agents.yaml      # Agent definitions
│   └── tasks.yaml       # Task definitions
├── src/
│   ├── __init__.py
│   ├── main.py          # Entry point
│   ├── crew.py          # Crew orchestration
│   ├── agents/          # Agent implementations
│   └── tasks/           # Task implementations
├── outputs/             # Task outputs
├── pyproject.toml
└── requirements.txt
\`\`\`

---

*Generated by Visual Agent Builder on ${this.formatDate()}*
`;
  }

  private generatePyProject(): string {
    const name = this.slugify(this.config.name);
    return `[project]
name = "${name}"
version = "${this.config.version}"
description = "${this.config.description || 'CrewAI workflow'}"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "crewai>=0.30.0",
    "crewai-tools>=0.2.0",
    "langchain>=0.2.0",
    "langchain-anthropic>=0.1.0",
    "python-dotenv>=1.0.0",
    "pyyaml>=6.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "black>=24.0.0",
    "ruff>=0.3.0",
]

[project.scripts]
run = "src.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
`;
  }

  private generateRequirements(): string {
    return `crewai>=0.30.0
crewai-tools>=0.2.0
langchain>=0.2.0
langchain-anthropic>=0.1.0
python-dotenv>=1.0.0
pyyaml>=6.0.0
`;
  }

  private generateEnvExample(): string {
    return `# Required
ANTHROPIC_API_KEY=your-anthropic-api-key

# Optional
OPENAI_API_KEY=your-openai-api-key
`;
  }

  private generateAgentsYaml(): string {
    const agents = this.getNodesByType('AGENT');
    const lines: string[] = [
      `# Agent Definitions for ${this.config.name}`,
      '# Generated by Visual Agent Builder',
      '',
    ];

    for (const agent of agents) {
      const config = agent.data.config || {};
      const name = this.slugify(config.name || agent.data.label);
      const displayName = config.name || agent.data.label;

      lines.push(`${name}:`);
      lines.push(`  role: "${config.role || 'Specialist'}"`);
      lines.push('  goal: >');
      lines.push(`    ${config.description || `Complete tasks as ${displayName}`}`);
      lines.push('  backstory: >');
      lines.push(`    You are ${displayName}, an expert in your domain.`);
      if (config.systemPrompt) {
        lines.push(`    ${config.systemPrompt.split('\n')[0]}`);
      }
      lines.push(`  llm: anthropic/${config.model || 'claude-sonnet-4-20250514'}`);
      lines.push(`  temperature: ${config.temperature ?? 0.7}`);
      lines.push(`  max_tokens: ${config.maxTokens || 4096}`);

      if (config.tools && config.tools.length > 0) {
        lines.push('  tools:');
        config.tools.forEach((tool: string) => {
          lines.push(`    - ${tool.toLowerCase()}`);
        });
      }

      lines.push(`  allow_delegation: ${config.role === 'leader' || config.role === 'orchestrator'}`);
      lines.push('  verbose: true');
      lines.push('  memory: true');
      lines.push('');
    }

    return lines.join('\n');
  }

  private generateTasksYaml(): string {
    const agents = this.getNodesByType('AGENT');
    const lines: string[] = [
      `# Task Definitions for ${this.config.name}`,
      '# Generated by Visual Agent Builder',
      '',
    ];

    // Generate a task for each agent
    for (const agent of agents) {
      const config = agent.data.config || {};
      const agentName = this.slugify(config.name || agent.data.label);
      const displayName = config.name || agent.data.label;

      lines.push(`${agentName}_task:`);
      lines.push('  description: >');
      lines.push(`    Perform the assigned task as ${displayName}.`);
      lines.push(`    ${config.description || ''}`);
      lines.push('  expected_output: >');
      lines.push(`    A complete and well-structured result from ${displayName}.`);
      lines.push(`  agent: ${agentName}`);
      lines.push(`  output_file: outputs/${agentName}_output.md`);
      lines.push('');
    }

    return lines.join('\n');
  }

  private generateMain(): string {
    return `"""
Main entry point for ${this.config.name} CrewAI workflow.
Generated by Visual Agent Builder.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from dotenv import load_dotenv

from .crew import run_crew


def main():
    """CLI entry point."""
    load_dotenv()

    parser = argparse.ArgumentParser(
        description="${this.config.description || 'CrewAI workflow'}"
    )
    parser.add_argument(
        "topic",
        nargs="?",
        default="",
        help="Topic or task for the crew"
    )
    parser.add_argument(
        "--process",
        choices=["sequential", "hierarchical"],
        default="sequential",
        help="Crew process type"
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        default=True,
        help="Enable verbose output"
    )

    args = parser.parse_args()

    if not args.topic:
        print("Error: Please provide a topic or task")
        return 1

    # Ensure output directory exists
    Path("outputs").mkdir(exist_ok=True)

    print(f"\\n🚀 Starting crew for: {args.topic}\\n")

    result = run_crew(
        topic=args.topic,
        process=args.process,
        verbose=args.verbose,
    )

    print(f"\\n✅ Crew completed! Outputs saved to: outputs/\\n")

    return 0


if __name__ == "__main__":
    exit(main())
`;
  }

  private generateCrew(): string {
    const agents = this.getNodesByType('AGENT');
    const options = this.config.frameworkOptions.crewai!;

    // Generate agent imports and instantiations
    const agentImports = agents
      .map((a) => {
        const name = this.slugify(a.data.config?.name || a.data.label);
        return `from .agents.${name} import create_${name}_agent`;
      })
      .join('\n');

    // Generate task imports and instantiations
    const taskImports = agents
      .map((a) => {
        const name = this.slugify(a.data.config?.name || a.data.label);
        return `from .tasks.${name}_task import create_${name}_task`;
      })
      .join('\n');

    return `"""
Crew orchestration for ${this.config.name}.
Generated by Visual Agent Builder.
"""

from __future__ import annotations

from pathlib import Path
from crewai import Agent, Crew, Process, Task

${agentImports}
${taskImports}


# =============================================================================
# Crew Factory
# =============================================================================

def create_crew(process: str = "sequential") -> Crew:
    """Create and return the crew."""

    # Create agents
    agents = {
${agents.map((a) => `        "${this.slugify(a.data.config?.name || a.data.label)}": create_${this.slugify(a.data.config?.name || a.data.label)}_agent()`).join(',\n')}
    }

    # Create tasks
    tasks = [
${agents.map((a) => `        create_${this.slugify(a.data.config?.name || a.data.label)}_task(agents["${this.slugify(a.data.config?.name || a.data.label)}"])`).join(',\n')}
    ]

    # Create crew
    process_type = Process.hierarchical if process == "hierarchical" else Process.sequential

    return Crew(
        agents=list(agents.values()),
        tasks=tasks,
        process=process_type,
        verbose=True,
        memory=${options.memoryEnabled},
    )


def run_crew(topic: str, process: str = "sequential", verbose: bool = True) -> dict:
    """Run the crew with a given topic."""

    crew = create_crew(process)
    result = crew.kickoff(inputs={"topic": topic})

    return {
        "result": result,
        "outputs_dir": "outputs",
    }
`;
  }

  private generateAgentClasses(): void {
    const agents = this.getNodesByType('AGENT');

    this.addFile('src/agents/__init__.py', '');

    for (const agent of agents) {
      const config = agent.data.config || {};
      const name = this.slugify(config.name || agent.data.label);
      const displayName = config.name || agent.data.label;

      const content = `"""
${displayName} agent implementation.
Generated by Visual Agent Builder.
"""

from crewai import Agent
from crewai_tools import WebsiteSearchTool, FileReadTool


def create_${name}_agent() -> Agent:
    """Create and return the ${displayName} agent."""

    return Agent(
        role="${config.role || 'Specialist'}",
        goal="${config.description || `Complete tasks as ${displayName}`}",
        backstory="""You are ${displayName}, an expert in your domain.
${config.systemPrompt || ''}""",
        llm="anthropic/${config.model || 'claude-sonnet-4-20250514'}",
        temperature=${config.temperature ?? 0.7},
        max_tokens=${config.maxTokens || 4096},
        tools=[],  # Add tools as needed
        allow_delegation=${config.role === 'leader' || config.role === 'orchestrator'},
        verbose=True,
        memory=True,
    )
`;

      this.addFile(`src/agents/${name}.py`, content);
    }
  }

  private generateTaskClasses(): void {
    const agents = this.getNodesByType('AGENT');

    this.addFile('src/tasks/__init__.py', '');

    for (const agent of agents) {
      const config = agent.data.config || {};
      const name = this.slugify(config.name || agent.data.label);
      const displayName = config.name || agent.data.label;

      const content = `"""
${displayName} task implementation.
Generated by Visual Agent Builder.
"""

from crewai import Agent, Task


def create_${name}_task(agent: Agent) -> Task:
    """Create and return the ${displayName} task."""

    return Task(
        description="""Perform the assigned task as ${displayName}.
${config.description || ''}

Topic: {topic}
""",
        expected_output="A complete and well-structured result.",
        agent=agent,
        output_file="outputs/${name}_output.md",
    )
`;

      this.addFile(`src/tasks/${name}_task.py`, content);
    }
  }
}
